"""add decision request

Revision ID: 3ddfdf1596b6
Revises: 8a6ce609383c
Create Date: 2026-08-31 11:07:22.574259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddfdf1596b6'
down_revision: Union[str, None] = '8a6ce609383c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freight_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_request_id', sa.Integer(), nullable=False),
    sa.Column('vessel_type', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=150), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('horizon', sa.Enum('SHORT_TERM', 'MEDIUM_TERM', name='forecast_horizon_enum'), nullable=False),
    sa.Column('predicted_freight_rate', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('lower_bound', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('upper_bound', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.Enum('RISING', 'FALLING', 'STABLE', name='forecast_direction_enum'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_forecasts_decision_request_id'), 'freight_forecasts', ['decision_request_id'], unique=False)
    op.create_index(op.f('ix_freight_forecasts_destination'), 'freight_forecasts', ['destination'], unique=False)
    op.create_index(op.f('ix_freight_forecasts_forecast_date'), 'freight_forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_freight_forecasts_origin'), 'freight_forecasts', ['origin'], unique=False)
    op.create_index(op.f('ix_freight_forecasts_vessel_type'), 'freight_forecasts', ['vessel_type'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_request_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('VESSEL', 'ROUTE', 'PORT', 'CHARTER', 'SPLIT_CARGO', 'COMBINED', name='recommendation_type_enum'), nullable=False),
    sa.Column('recommended_vessel_type', sa.String(length=50), nullable=True),
    sa.Column('recommended_origin', sa.String(length=150), nullable=True),
    sa.Column('recommended_destination', sa.String(length=150), nullable=True),
    sa.Column('recommended_route', sa.String(length=255), nullable=True),
    sa.Column('charter_strategy', sa.Enum('SPOT', 'SHORT_TERM', 'MEDIUM_TERM', 'MULTI_VOYAGE', name='charter_strategy_enum'), nullable=True),
    sa.Column('recommended_voyages', sa.Integer(), nullable=True),
    sa.Column('recommended_duration_days', sa.Integer(), nullable=True),
    sa.Column('estimated_freight_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('estimated_landed_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('estimated_cost_per_ton', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('constraints_considered', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_charter_strategy'), 'recommendations', ['charter_strategy'], unique=False)
    op.create_index(op.f('ix_recommendations_decision_request_id'), 'recommendations', ['decision_request_id'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_type'), 'recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('ix_recommendations_recommended_vessel_type'), 'recommendations', ['recommended_vessel_type'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_request_id', sa.Integer(), nullable=False),
    sa.Column('risk_type', sa.Enum('FREIGHT_VOLATILITY', 'PORT_CONGESTION', 'WEATHER', 'CYCLONE', 'GEOPOLITICAL', 'FUEL', 'COMMODITY', 'SEASONAL', 'OPERATIONAL', name='risk_type_enum'), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level_enum'), nullable=False),
    sa.Column('probability', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('impact_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mitigation_strategy', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_decision_request_id'), 'risk_assessments', ['decision_request_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_level'), 'risk_assessments', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_type'), 'risk_assessments', ['risk_type'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_request_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('simulation_type', sa.Enum('FREIGHT_RATE', 'PORT_CONGESTION', 'DEMAND', 'FUEL_PRICE', 'COMBINED', name='simulation_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('freight_rate_change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('congestion_change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('demand_change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fuel_price_change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('baseline_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('simulated_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('cost_difference', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('cost_difference_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('baseline_transit_days', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('simulated_transit_days', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('baseline_risk_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('simulated_risk_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('recommended_action', sa.String(length=255), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_decision_request_id'), 'simulations', ['decision_request_id'], unique=False)
    op.create_index(op.f('ix_simulations_simulation_type'), 'simulations', ['simulation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulations_simulation_type'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_decision_request_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_risk_assessments_risk_type'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_level'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_decision_request_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_recommendations_recommended_vessel_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_recommendation_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_decision_request_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_charter_strategy'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_freight_forecasts_vessel_type'), table_name='freight_forecasts')
    op.drop_index(op.f('ix_freight_forecasts_origin'), table_name='freight_forecasts')
    op.drop_index(op.f('ix_freight_forecasts_forecast_date'), table_name='freight_forecasts')
    op.drop_index(op.f('ix_freight_forecasts_destination'), table_name='freight_forecasts')
    op.drop_index(op.f('ix_freight_forecasts_decision_request_id'), table_name='freight_forecasts')
    op.drop_table('freight_forecasts')
    # ### end Alembic commands ###
