"""add market data tables

Revision ID: 885c1edf71c0
Revises: 9d37adff93be
Create Date: 2026-08-31 10:51:28.514564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885c1edf71c0'
down_revision: Union[str, None] = '9d37adff93be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bunker_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(length=150), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('price_usd_ton', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bunker_prices_date'), 'bunker_prices', ['date'], unique=False)
    op.create_index(op.f('ix_bunker_prices_fuel_type'), 'bunker_prices', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_bunker_prices_region'), 'bunker_prices', ['region'], unique=False)
    op.create_table('commodities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodities_name'), 'commodities', ['name'], unique=True)
    op.create_table('freight_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('origin', sa.String(length=150), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=False),
    sa.Column('vessel_type', sa.String(length=50), nullable=False),
    sa.Column('freight_rate', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_rates_date'), 'freight_rates', ['date'], unique=False)
    op.create_index(op.f('ix_freight_rates_destination'), 'freight_rates', ['destination'], unique=False)
    op.create_index(op.f('ix_freight_rates_origin'), 'freight_rates', ['origin'], unique=False)
    op.create_index(op.f('ix_freight_rates_vessel_type'), 'freight_rates', ['vessel_type'], unique=False)
    op.create_table('commodity_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('demand_index', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodity_prices_commodity_id'), 'commodity_prices', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_commodity_prices_date'), 'commodity_prices', ['date'], unique=False)
    op.create_index(op.f('ix_commodity_prices_region'), 'commodity_prices', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commodity_prices_region'), table_name='commodity_prices')
    op.drop_index(op.f('ix_commodity_prices_date'), table_name='commodity_prices')
    op.drop_index(op.f('ix_commodity_prices_commodity_id'), table_name='commodity_prices')
    op.drop_table('commodity_prices')
    op.drop_index(op.f('ix_freight_rates_vessel_type'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_origin'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_destination'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_date'), table_name='freight_rates')
    op.drop_table('freight_rates')
    op.drop_index(op.f('ix_commodities_name'), table_name='commodities')
    op.drop_table('commodities')
    op.drop_index(op.f('ix_bunker_prices_region'), table_name='bunker_prices')
    op.drop_index(op.f('ix_bunker_prices_fuel_type'), table_name='bunker_prices')
    op.drop_index(op.f('ix_bunker_prices_date'), table_name='bunker_prices')
    op.drop_table('bunker_prices')
    # ### end Alembic commands ###
