"""add decision request

Revision ID: 8a6ce609383c
Revises: c19e1d91c4fb
Create Date: 2026-08-31 11:00:22.532725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a6ce609383c'
down_revision: Union[str, None] = 'c19e1d91c4fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_reference', sa.String(length=50), nullable=False),
    sa.Column('commodity', sa.String(length=100), nullable=False),
    sa.Column('cargo_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('origin', sa.String(length=150), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=False),
    sa.Column('earliest_loading_date', sa.Date(), nullable=False),
    sa.Column('latest_delivery_date', sa.Date(), nullable=False),
    sa.Column('contract_preference', sa.Enum('SPOT', 'SHORT_TERM', 'MEDIUM_TERM', 'MULTI_VOYAGE', 'AUTO', name='contract_preference_enum'), nullable=False),
    sa.Column('contract_duration_days', sa.Integer(), nullable=True),
    sa.Column('expected_voyages', sa.Integer(), nullable=True),
    sa.Column('preferred_vessel_type', sa.String(length=50), nullable=True),
    sa.Column('target_freight_rate', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('max_budget', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='request_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_requests_commodity'), 'decision_requests', ['commodity'], unique=False)
    op.create_index(op.f('ix_decision_requests_destination'), 'decision_requests', ['destination'], unique=False)
    op.create_index(op.f('ix_decision_requests_origin'), 'decision_requests', ['origin'], unique=False)
    op.create_index(op.f('ix_decision_requests_preferred_vessel_type'), 'decision_requests', ['preferred_vessel_type'], unique=False)
    op.create_index(op.f('ix_decision_requests_request_reference'), 'decision_requests', ['request_reference'], unique=True)
    op.create_index(op.f('ix_decision_requests_status'), 'decision_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_requests_status'), table_name='decision_requests')
    op.drop_index(op.f('ix_decision_requests_request_reference'), table_name='decision_requests')
    op.drop_index(op.f('ix_decision_requests_preferred_vessel_type'), table_name='decision_requests')
    op.drop_index(op.f('ix_decision_requests_origin'), table_name='decision_requests')
    op.drop_index(op.f('ix_decision_requests_destination'), table_name='decision_requests')
    op.drop_index(op.f('ix_decision_requests_commodity'), table_name='decision_requests')
    op.drop_table('decision_requests')
    # ### end Alembic commands ###
