"""create initial port vessel route tables

Revision ID: 9d37adff93be
Revises: 
Create Date: 2026-08-31 10:37:35.614339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d37adff93be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('max_draft', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_loa', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('max_beam', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('berth_count', sa.Integer(), nullable=False),
    sa.Column('cargo_handling_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('storage_capacity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('turnaround_time', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('congestion_status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ports_congestion_status'), 'ports', ['congestion_status'], unique=False)
    op.create_index(op.f('ix_ports_country'), 'ports', ['country'], unique=False)
    op.create_index(op.f('ix_ports_name'), 'ports', ['name'], unique=False)
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_type', sa.String(length=50), nullable=False),
    sa.Column('deadweight_tons', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cargo_capacity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loa', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('beam', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('draft', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('speed', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fuel_consumption', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessels_vessel_type'), 'vessels', ['vessel_type'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_port_id', sa.Integer(), nullable=False),
    sa.Column('destination_port_id', sa.Integer(), nullable=False),
    sa.Column('distance_nm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_transit_days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['destination_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['origin_port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_destination_port_id'), 'routes', ['destination_port_id'], unique=False)
    op.create_index(op.f('ix_routes_origin_port_id'), 'routes', ['origin_port_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_origin_port_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination_port_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_vessels_vessel_type'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_ports_name'), table_name='ports')
    op.drop_index(op.f('ix_ports_country'), table_name='ports')
    op.drop_index(op.f('ix_ports_congestion_status'), table_name='ports')
    op.drop_table('ports')
    # ### end Alembic commands ###
