"""add operational and market signal tables

Revision ID: c19e1d91c4fb
Revises: 885c1edf71c0
Create Date: 2026-08-31 10:55:22.535281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19e1d91c4fb'
down_revision: Union[str, None] = '885c1edf71c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=150), nullable=True),
    sa.Column('commodity', sa.String(length=100), nullable=True),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('sentiment', sa.String(length=30), nullable=False),
    sa.Column('impact', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_signals_commodity'), 'market_signals', ['commodity'], unique=False)
    op.create_index(op.f('ix_market_signals_impact'), 'market_signals', ['impact'], unique=False)
    op.create_index(op.f('ix_market_signals_region'), 'market_signals', ['region'], unique=False)
    op.create_index(op.f('ix_market_signals_sentiment'), 'market_signals', ['sentiment'], unique=False)
    op.create_index(op.f('ix_market_signals_signal_type'), 'market_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_market_signals_source'), 'market_signals', ['source'], unique=False)
    op.create_index(op.f('ix_market_signals_timestamp'), 'market_signals', ['timestamp'], unique=False)
    op.create_table('port_congestion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('port', sa.String(length=150), nullable=False),
    sa.Column('congestion_level', sa.String(length=30), nullable=False),
    sa.Column('vessel_waiting', sa.Integer(), nullable=False),
    sa.Column('average_wait_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('berth_utilization', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_port_congestion_congestion_level'), 'port_congestion', ['congestion_level'], unique=False)
    op.create_index(op.f('ix_port_congestion_port'), 'port_congestion', ['port'], unique=False)
    op.create_index(op.f('ix_port_congestion_timestamp'), 'port_congestion', ['timestamp'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(length=150), nullable=False),
    sa.Column('wind', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('wave', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('storm', sa.Boolean(), nullable=False),
    sa.Column('cyclone', sa.Boolean(), nullable=False),
    sa.Column('weather_risk', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_date'), 'weather', ['date'], unique=False)
    op.create_index(op.f('ix_weather_region'), 'weather', ['region'], unique=False)
    op.create_index(op.f('ix_weather_weather_risk'), 'weather', ['weather_risk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_weather_risk'), table_name='weather')
    op.drop_index(op.f('ix_weather_region'), table_name='weather')
    op.drop_index(op.f('ix_weather_date'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_port_congestion_timestamp'), table_name='port_congestion')
    op.drop_index(op.f('ix_port_congestion_port'), table_name='port_congestion')
    op.drop_index(op.f('ix_port_congestion_congestion_level'), table_name='port_congestion')
    op.drop_table('port_congestion')
    op.drop_index(op.f('ix_market_signals_timestamp'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_source'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_signal_type'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_sentiment'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_region'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_impact'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_commodity'), table_name='market_signals')
    op.drop_table('market_signals')
    # ### end Alembic commands ###
