"""initial schema

Revision ID: ca9980a2869f
Revises: 
Create Date: 2026-09-06 18:49:56.543324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9980a2869f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bunker_prices',
    sa.Column('port_name', sa.String(length=100), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price_usd_per_ton', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bunker_prices_port_name'), 'bunker_prices', ['port_name'], unique=False)
    op.create_table('commodities',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('decision_requests',
    sa.Column('commodity', sa.String(length=100), nullable=False),
    sa.Column('cargo_quantity', sa.Float(), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('earliest_loading_date', sa.Date(), nullable=False),
    sa.Column('latest_delivery_date', sa.Date(), nullable=False),
    sa.Column('contract_preference', sa.String(length=30), nullable=False),
    sa.Column('contract_duration_days', sa.Integer(), nullable=True),
    sa.Column('expected_voyages', sa.Integer(), nullable=True),
    sa.Column('preferred_vessel_type', sa.String(length=50), nullable=True),
    sa.Column('target_freight_rate', sa.Float(), nullable=True),
    sa.Column('max_budget', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freight_rates',
    sa.Column('vessel_class', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate_usd_per_ton', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_rates_destination'), 'freight_rates', ['destination'], unique=False)
    op.create_index(op.f('ix_freight_rates_origin'), 'freight_rates', ['origin'], unique=False)
    op.create_index(op.f('ix_freight_rates_rate_date'), 'freight_rates', ['rate_date'], unique=False)
    op.create_index(op.f('ix_freight_rates_vessel_class'), 'freight_rates', ['vessel_class'], unique=False)
    op.create_table('market_signals',
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('port_congestions',
    sa.Column('port_name', sa.String(length=100), nullable=False),
    sa.Column('observed_date', sa.Date(), nullable=False),
    sa.Column('congestion_index', sa.Float(), nullable=False),
    sa.Column('avg_wait_days', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_port_congestions_port_name'), 'port_congestions', ['port_name'], unique=False)
    op.create_table('ports',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('max_draft', sa.Float(), nullable=False),
    sa.Column('max_loa', sa.Float(), nullable=False),
    sa.Column('max_beam', sa.Float(), nullable=False),
    sa.Column('berth_count', sa.Integer(), nullable=False),
    sa.Column('cargo_handling_rate_tons_per_day', sa.Float(), nullable=False),
    sa.Column('storage_capacity_tons', sa.Float(), nullable=False),
    sa.Column('congestion_baseline', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ports_name'), 'ports', ['name'], unique=True)
    op.create_table('routes',
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('distance_nm', sa.Float(), nullable=False),
    sa.Column('typical_transit_days', sa.Float(), nullable=False),
    sa.Column('piracy_risk_index', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_destination'), 'routes', ['destination'], unique=False)
    op.create_index(op.f('ix_routes_origin'), 'routes', ['origin'], unique=False)
    op.create_table('vessels',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('vessel_class', sa.String(length=50), nullable=False),
    sa.Column('dwt', sa.Float(), nullable=False),
    sa.Column('loa', sa.Float(), nullable=False),
    sa.Column('beam', sa.Float(), nullable=False),
    sa.Column('draft', sa.Float(), nullable=False),
    sa.Column('current_position', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessels_vessel_class'), 'vessels', ['vessel_class'], unique=False)
    op.create_table('weather_records',
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('observed_date', sa.Date(), nullable=False),
    sa.Column('cyclone_risk_index', sa.Float(), nullable=False),
    sa.Column('rough_sea_index', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_records_region'), 'weather_records', ['region'], unique=False)
    op.create_table('commodity_prices',
    sa.Column('commodity_id', sa.String(length=36), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price_usd_per_ton', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_audits',
    sa.Column('decision_request_id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freight_forecasts',
    sa.Column('decision_request_id', sa.String(length=36), nullable=False),
    sa.Column('vessel_class', sa.String(length=50), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('predicted_rate', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idle_vessels',
    sa.Column('decision_request_id', sa.String(length=36), nullable=False),
    sa.Column('vessel_class', sa.String(length=50), nullable=False),
    sa.Column('idle_probability', sa.Float(), nullable=False),
    sa.Column('expected_idle_days', sa.Float(), nullable=False),
    sa.Column('deadhead_distance_nm', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.String(length=50), nullable=False),
    sa.Column('estimated_savings', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landed_costs',
    sa.Column('decision_request_id', sa.String(length=36), nullable=False),
    sa.Column('vessel_class', sa.String(length=50), nullable=False),
    sa.Column('freight_cost', sa.Float(), nullable=False),
    sa.Column('port_charges', sa.Float(), nullable=False),
    sa.Column('insurance', sa.Float(), nullable=False),
    sa.Column('levies', sa.Float(), nullable=False),
    sa.Column('bunker_cost', sa.Float(), nullable=False),
    sa.Column('other_costs', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_ton', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_entries',
    sa.Column('decision_request_id', sa.String(length=36), nullable=False),
    sa.Column('recommended_action', sa.String(length=20), nullable=False),
    sa.Column('ideal_entry_window_start', sa.Date(), nullable=True),
    sa.Column('ideal_entry_window_end', sa.Date(), nullable=True),
    sa.Column('expected_rate_change_pct', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('decision_request_id', sa.String(length=36), nullable=False),
    sa.Column('risk_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulations',
    sa.Column('decision_request_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_name', sa.String(length=100), nullable=False),
    sa.Column('scenario_params', sa.Text(), nullable=False),
    sa.Column('baseline_cost', sa.Float(), nullable=False),
    sa.Column('scenario_cost', sa.Float(), nullable=False),
    sa.Column('cost_delta', sa.Float(), nullable=False),
    sa.Column('delay_impact_days', sa.Float(), nullable=False),
    sa.Column('risk_impact', sa.String(length=20), nullable=False),
    sa.Column('recommendation_impact', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('split_cargos',
    sa.Column('decision_request_id', sa.String(length=36), nullable=False),
    sa.Column('option_label', sa.String(length=50), nullable=False),
    sa.Column('vessel_composition', sa.Text(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('decision_request_id', sa.String(length=36), nullable=False),
    sa.Column('landed_cost_id', sa.String(length=36), nullable=True),
    sa.Column('vessel_class', sa.String(length=50), nullable=False),
    sa.Column('origin_port', sa.String(length=100), nullable=False),
    sa.Column('destination_port', sa.String(length=100), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=True),
    sa.Column('charter_strategy', sa.String(length=30), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('is_feasible', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_request_id'], ['decision_requests.id'], ),
    sa.ForeignKeyConstraint(['landed_cost_id'], ['landed_costs.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_table('split_cargos')
    op.drop_table('simulations')
    op.drop_table('risk_assessments')
    op.drop_table('market_entries')
    op.drop_table('landed_costs')
    op.drop_table('idle_vessels')
    op.drop_table('freight_forecasts')
    op.drop_table('decision_audits')
    op.drop_table('commodity_prices')
    op.drop_index(op.f('ix_weather_records_region'), table_name='weather_records')
    op.drop_table('weather_records')
    op.drop_index(op.f('ix_vessels_vessel_class'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_routes_origin'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_ports_name'), table_name='ports')
    op.drop_table('ports')
    op.drop_index(op.f('ix_port_congestions_port_name'), table_name='port_congestions')
    op.drop_table('port_congestions')
    op.drop_table('market_signals')
    op.drop_index(op.f('ix_freight_rates_vessel_class'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_rate_date'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_origin'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_destination'), table_name='freight_rates')
    op.drop_table('freight_rates')
    op.drop_table('decision_requests')
    op.drop_table('commodities')
    op.drop_index(op.f('ix_bunker_prices_port_name'), table_name='bunker_prices')
    op.drop_table('bunker_prices')
    # ### end Alembic commands ###
